/// <reference path="../pb_data/types.d.ts" />

// GET /flags
// Called by LoginManager.getFlags — returns feature flags from server.
// Self-hosted: return empty flags (all features use defaults).
routerAdd("GET", "/flags", (c) => {
    return c.json(200, [])
})


// GET /health
// Health check endpoint for self-hosted Relay plugin.
// Returns 200 with version info. Query param ?version=... is echoed back.
routerAdd("GET", "/health", (c) => {
    const version = c.queryParam("version") || ""
    return c.json(200, { status: "ok", version })
})


// GET /whoami
// Called by LoginManager.whoami for debug/logging purposes.
routerAdd("GET", "/whoami", (c) => {
    const info = $apis.requestInfo(c)
    if (!info.authRecord) {
        return c.json(401, { error: "Unauthorized" })
    }
    return c.json(200, {
        id:    info.authRecord.id,
        email: info.authRecord.get("email"),
        name:  info.authRecord.get("name"),
    })
})


// GET /templates/relay.toml
// Fetched by SelfHostModalContent.svelte to show relay server config to the operator.
// Returns a relay.toml template pre-filled with this control plane's public key.
routerAdd("GET", "/templates/relay.toml", (c) => {
    const publicKey = $os.getenv("RELAY_PUBLIC_KEY") || "<RELAY_PUBLIC_KEY>"
    const keyId     = $os.getenv("RELAY_KEY_ID")     || "self_hosted"
    const keyType   = $os.getenv("RELAY_KEY_TYPE")   || "EdDSA"

    const toml = `# Relay Server Configuration
# Generated by relay-control-plane
#
# Place this file at /app/relay.toml on your relay server.

[server]
url = "{url}"
host = "0.0.0.0"
port = 8080

# Trust tokens issued by this control plane
[[auth]]
key_id = "${keyId}"
public_key = "${publicKey}"

[store]
# Uncomment and configure for S3-compatible storage:
# type = "aws"
# bucket = "my-bucket"
# region = "us-east-1"
# access_key_id = ""
# secret_access_key = ""
`

    c.response().header().set("Content-Type", "text/plain; charset=utf-8")
    return c.string(200, toml)
})


// GET /api/oauth2-redirect
// OAuth2 callback endpoint. After the user authenticates with the provider,
// they are redirected here with ?code=...&state=... The plugin polls the
// code_exchange collection until this record appears, then calls authWithOAuth2Code.
routerAdd("GET", "/api/oauth2-redirect", (c) => {
    const code  = c.queryParam("code")
    const state = c.queryParam("state")

    if (code && state) {
        try {
            const coll = $app.dao().findCollectionByNameOrId("code_exchange")
            const rec  = new Record(coll)
            rec.setId(state.slice(0, 15))
            rec.set("code", code)
            rec.set("state", state)
            $app.dao().saveRecord(rec)
        } catch (err) {
            // Likely ID collision (two OAuth flows sharing first 15 chars of state) or duplicate retry.
            // Silent ignore preserves idempotency on retry; log for collision visibility.
            console.log("[oauth2-redirect] save failed for id=" + state.slice(0, 15) + ":", err.message)
        }
    }

    c.response().header().set("Content-Type", "text/html; charset=utf-8")
    return c.string(200, `<!DOCTYPE html>
<html>
<head><title>Authentication complete</title>
<style>body{font-family:system-ui;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:#1a1a2e}
.card{background:#16213e;color:#e0e0e0;padding:2rem 3rem;border-radius:12px;text-align:center}
h2{margin:0 0 .5rem;color:#a78bfa}p{margin:0;color:#9ca3af}</style></head>
<body><div class="card"><h2>Authentication complete</h2><p>You can close this tab and return to Obsidian.</p></div>
<script>setTimeout(()=>window.close(),1500)</script>
</body></html>`)
})


// POST /api/subscription/:id/token
// Legacy endpoint called by RelayManager.getSubscriptionToken.
// Returns a simple token string for subscription-level access.
routerAdd("POST", "/api/subscription/:id/token", (c) => {
    const info = $apis.requestInfo(c)
    if (!info.authRecord) {
        return c.json(401, { error: "Unauthorized" })
    }

    const subId = c.pathParam("id")
    let sub
    try {
        sub = $app.dao().findRecordById("subscriptions", subId)
    } catch (_) {
        return c.json(404, { error: "Subscription not found" })
    }

    // Return the stored token, or the server auth token as fallback
    const token = sub.get("token") || $os.getenv("RELAY_SERVER_AUTH") || ""
    return c.json(200, { token })
}, $apis.requireRecordAuth())


// GET /api/superuser/settings
// View current settings (for debugging)
routerAdd("GET", "/api/superuser/settings", (c) => {
    try {
        const settings = $app.dao().findSettings()
        const authProviders = {}
        for (const key of Object.keys(settings)) {
            if (key.endsWith("Auth") && settings[key]) {
                const p = settings[key]
                authProviders[key] = {
                    enabled: p.enabled,
                    clientId: p.clientId,
                    clientSecret: p.clientSecret ? "***" : "",
                    redirectUrl: p.redirectUrl,
                    displayName: p.displayName,
                }
            }
        }
        return c.json(200, {
            authProviders,
            meta: {
                appName: settings.meta?.appName,
                appUrl: settings.meta?.appUrl,
            },
        })
    } catch (err) {
        return c.json(500, { error: err.message, stack: err.stack })
    }
}, $apis.requireAdminAuth())


// GET /api/superuser/oauth
// Check if OAuth is configured (deprecated - use entrypoint or admin UI)
routerAdd("GET", "/api/superuser/oauth", (c) => {
    const settings = $app.dao().findSettings()
    const providers = []
    for (const key of Object.keys(settings)) {
        if (key.endsWith("Auth") && settings[key]?.clientId) {
            providers.push(key.replace("Auth", ""))
        }
    }
    return c.json(200, {
        configured: providers.length > 0,
        providers,
    })
}, $apis.requireAdminAuth())


// POST /api/superuser/oauth
routerAdd("POST", "/api/superuser/oauth", (c) => {
    const body = c.request.body
    const provider = body?.provider
    const clientId = body?.clientId
    const clientSecret = body?.clientSecret
    const redirectUrl = body?.redirectUrl

    if (!provider || !clientId || !clientSecret) {
        return c.json(400, { error: "Missing provider, clientId, or clientSecret" })
    }

    try {
        const settings = $app.dao().findSettings()
        const authKey = provider + "Auth"

        settings[authKey] = {
            enabled: true,
            clientId,
            clientSecret,
        }
        if (redirectUrl) {
            settings[authKey].redirectUrl = redirectUrl
        }

        $app.dao().saveSettings(settings)

        return c.json(200, { ok: true, provider, authKey })
    } catch (err) {
        return c.json(500, { error: err.message, stack: err.stack })
    }
}, $apis.requireAdminAuth())

